server:
  port: 8080
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "auth"
    schema: "public"
    username: creditUserData #"creditSolicitudData"
    password: "za4iLVvR8qVq4yQv"
spring:
  application:
    name: "CrediYa_Auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  level:
    root: WARN
    co.com.crediya.api.logger.GlobalLogger: INFO
routes:
  user:
    base: /api/v1/usuarios
    document: /api/v1/usuarios/document
    login: /api/v1/login
    validateToken: /api/v1/validateToken
    allUsers: /api/v1/usuarios/allUsers
    someUsers: /api/v1/usuarios/mapEmails

jwt:
  secret: "yW9kMHFmQmQzUGxwM0NnNGcyZ1kzZzdXwqGZz/GePgs="
  expiration: 3600000